DbBicyclesLab/Models/BicycleModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace DbBicyclesLab.Models
{
    public partial class BicycleModel
    {
        public BicycleModel()
        {
            SizeColorModels = new HashSet<SizeColorModel>();
        }

        public int Id { get; set; }
        [Display(Name = "Вартість")]
        [Range(0, int.MaxValue, ErrorMessage = ErrorMessages.Range)]
        public int? Price { get; set; }
        [Display(Name = "Назва моделі")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        [StringLength(50, ErrorMessage = ErrorMessages.StringLength)]
        public string ModelName { get; set; }
        [Display(Name = "Рік випуску")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        [Range(1850, 9999, ErrorMessage = ErrorMessages.Range)]
        public int ModelYear { get; set; }
        [Display(Name = "Бренд")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        public int BrandId { get; set; }
        [Display(Name = "Для кого")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        public int GenderId { get; set; }
        [Display(Name = "Категорія")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        public int CategoryId { get; set; }
        [Display(Name = "Опис")]
        [StringLength(2500, ErrorMessage = ErrorMessages.StringLength)]
        public string Description { get; set; }
        [Display(Name ="Зображення")]
        public virtual byte[] Image { get; set; }
        [Display(Name = "Бренд")]
        public virtual Brand Brand { get; set; }
        [Display(Name = "Категорія")]
        public virtual Category Category { get; set; }
        [Display(Name = "Для кого")]
        public virtual Gender Gender { get; set; }
        public virtual ICollection<SizeColorModel> SizeColorModels { get; set; }
    }
}

DbBicyclesLab/Models/BicycleModelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace DbBicyclesLab.Models
{
    public class BicycleModelViewModel
    {
        public int Id { get; set; }
        public int? Price { get; set; }
        public string ModelName { get; set; }
        public int ModelYear { get; set; }
        public int BrandId { get; set; }
        public int GenderId { get; set; }
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<SizeColorModel> SizeColorModels { get; set; }
        public IFormFile Image { get; set; }
    }
}

DbBicyclesLab/ViewModels/BicycleModelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace DbBicyclesLab.Models
{
    public class BicycleModelViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Ціна")]
        public int? Price { get; set; }
        [Display(Name = "Назва")]
        public string ModelName { get; set; }
        [Display(Name = "Рік випуску")]
        public int ModelYear { get; set; }
        public int BrandId { get; set; }
        public int GenderId { get; set; }
        public int CategoryId { get; set; }
        [Display(Name = "Опис")]
        public string Description { get; set; }
        [Display(Name = "Бренд")]
        public virtual Brand Brand { get; set; }
        [Display(Name = "Категорія")]
        public virtual Category Category { get; set; }
        [Display(Name = "Для кого")]
        public virtual Gender Gender { get; set; }
        public virtual ICollection<SizeColorModel> SizeColorModels { get; set; }
        public IFormFile ImageFile { get; set; }
        public virtual byte[] Image { get; set; }
        [Display(Name = "Кількість")]
        public int? Quantity { get; set; }
        [Display(Name = "Доступні кольори")]
        public virtual ICollection<Color> Colors { get; set; }
        [Display(Name = "Доступні розміри")]
        public virtual ICollection<Size> Sizes { get; set; }

    }
}

DbBicyclesLab/Controllers/BicycleModelsController.cs
using System;
using System.Reflection;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;
using DbBicyclesLab.Models;
using System.IO;
using Microsoft.AspNetCore.Http;

using System.ComponentModel.DataAnnotations;
using ClosedXML.Excel;
using Xceed.Words.NET;
using Xceed.Document.NET;
using Xceed.Words;
using Xceed.Document;

namespace DbBicyclesLab.Controllers
{
    public class BicycleModelsController : Controller
    {
        private readonly DBBicyclesContext _context;

        public BicycleModelsController(DBBicyclesContext context)
        {
            _context = context;
        }

        private IEnumerable<BicycleModel> ApplyFilters(int? brand, int? category, int? gender, int? minPrice, int? maxPrice, string year)
        {
            IEnumerable<BicycleModel> bicycleModels =  from m in _context.BicycleModels
                                                       .Include(x => x.SizeColorModels)
                                                       .Include($"{ nameof(DBBicyclesContext.SizeColorModels)}.{nameof(SizeColorModel.Size)}")
                                                       .Include($"{ nameof(DBBicyclesContext.SizeColorModels)}.{nameof(SizeColorModel.Color)}")
                                                       .Include($"{ nameof(DBBicyclesContext.SizeColorModels)}.{nameof(SizeColorModel.Bicycles)}")
                                                       .Include(x => x.Brand)
                                                       .Include(x => x.Category)
                                                       .Include(x => x.Gender)
                                                       select m;
            if (brand != null)
            {
                bicycleModels = bicycleModels.Where(b => b.BrandId == brand);
            }
            if (category != null)
            {
                bicycleModels = bicycleModels.Where(b => b.CategoryId == category);
            }
            if (gender != null)
            {
                bicycleModels = bicycleModels.Where(b => b.GenderId == gender);
            }
            if (year != null && year != "Усі")
            {
                bicycleModels = bicycleModels.Where(b => b.ModelYear == int.Parse(year));
            }
            if (maxPrice != null && minPrice != null)
                bicycleModels = bicycleModels.Where(b => b.Price >= (minPrice) && b.Price <= (maxPrice));
            return bicycleModels;
        }

        // GET: BicycleModels
        public async Task<IActionResult> Index(int? brand, int? category, int? gender, int? minPrice, int? maxPrice, string year)
        {
            BicycleModelsListModelView listModelView = new BicycleModelsListModelView(_context);
            listModelView.BicycleModels = ApplyFilters(brand, category, gender, minPrice, maxPrice, year);
            return View(listModelView);
        }

        public async Task<IActionResult> CommonIndex(int? id)
        {
            var dBBicyclesContext = _context.BicycleModels.Include(b => b.Brand).Include(b => b.Category).Include(b => b.Gender);
            if (id != null)
                return View(await dBBicyclesContext.Where(m => m.CategoryId == id).ToListAsync());
            else
                return View(await dBBicyclesContext.ToListAsync());
        }

        // GET: BicycleModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bicycleModel = await _context.BicycleModels
                .Include(b => b.Brand)
                .Include(b => b.Category)
                .Include(b => b.Gender)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bicycleModel == null)
            {
                return NotFound();
            }

            return View(bicycleModel);
        }

        // GET: BicycleModels/Details/5
        public async Task<IActionResult> CommonDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bm = await _context.BicycleModels
                .Include(b => b.Brand)
                .Include(b => b.Category)
                .Include(b => b.Gender)
                .Include(b => b.SizeColorModels)
                .Include($"{ nameof(DBBicyclesContext.SizeColorModels)}.{nameof(SizeColorModel.Bicycles)}")
                .FirstOrDefaultAsync(m => m.Id == id);

            BicycleModelViewModel viewModel = new BicycleModelViewModel
            {
                Brand = bm.Brand,
                Category = bm.Category,
                Description = bm.Description,
                Gender = bm.Gender,
                Image = bm.Image,
                ModelName = bm.ModelName,
                ModelYear = bm.ModelYear,
                Price = bm.Price,
                SizeColorModels = bm.SizeColorModels
            };

            viewModel.Colors = bm.SizeColorModels.Select(s => _context.Colors.Find(s.ColorId)).Distinct().ToList();
            viewModel.Sizes = bm.SizeColorModels.Select(s => _context.Sizes.Find(s.SizeId)).Distinct().ToList();
            viewModel.Quantity = bm.SizeColorModels.Sum(s => s.Bicycles.Sum(b => b.Quantity));

            if (bm == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        // GET: BicycleModels/Create
        public IActionResult Create()
        {
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "BrandName");
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName");
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "GenderName");
            return View();
        }

        // POST: BicycleModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Price,ModelName,ModelYear,BrandId,GenderId,CategoryId,Description")] BicycleModel bicycleModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bicycleModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "BrandName", bicycleModel.BrandId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", bicycleModel.CategoryId);
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "GenderName", bicycleModel.GenderId);
            return View(bicycleModel);
        }*/

        [HttpPost]
        public IActionResult Create(BicycleModelViewModel bvm)
        {
            BicycleModel bicycleModel = new BicycleModel
            {
                BrandId = bvm.BrandId,
                CategoryId = bvm.CategoryId,
                GenderId = bvm.GenderId,

                Description = bvm.Description,
                Id = bvm.Id,
                ModelName = bvm.ModelName,
                ModelYear = bvm.ModelYear,
                Price = bvm.Price,
                SizeColorModels = bvm.SizeColorModels
            };

            if (ModelState.IsValid)
            {
                if (bvm.Image != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(bvm.ImageFile.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)bvm.Image.Length);
                    }
                    bicycleModel.Image = imageData;
                }
                _context.Add(bicycleModel);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "BrandName", bicycleModel.BrandId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", bicycleModel.CategoryId);
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "GenderName", bicycleModel.GenderId);
            return View(bicycleModel);
        }

        // GET: BicycleModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bicycleModel = await _context.BicycleModels.FindAsync(id);
            if (bicycleModel == null)
            {
                return NotFound();
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "BrandName", bicycleModel.BrandId);
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "CategoryName", bicycleModel.CategoryId);
            ViewData["GenderId"] = new SelectList(_context.Genders, "Id", "GenderName", bicycleModel.GenderId);
            return View(bicycleModel);
        }

        // POST: BicycleModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BicycleModelViewModel bicycleModel)//[Bind("Id,Price,ModelName,ModelYear,BrandId,GenderId,CategoryId,Description")] BicycleModel bicycleModel)
        {
            if (id != bicycleModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

DbBicyclesLab/Views/BicycleModels/CommonDetails.cshtml
@model DbBicyclesLab.Models.BicycleModelViewModel

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>@Html.DisplayFor(model => model.Brand.BrandName) @Html.DisplayFor(model => model.ModelName) @Html.DisplayFor(model => model.ModelYear)</h1>
            <div>
                <a asp-action="CommonIndex">Назад</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div style="position:relative; display:inline-flex;">
            <div class="col-6">
                @if (Model.Image != null)
                {
                    <img style='width:100%; height:auto; margin:10px; background-color:white;' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))" />
                }
            </div>
            <div class="col-6">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Дані</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Brand)
                            </td>
                            <td>
                                <a asp-controller="Brands" asp-action="CommonDetails" asp-route-id=@Model.Brand.Id>
                                    @Html.DisplayFor(model => model.Brand.BrandName)
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.ModelName)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.ModelName)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Brand.Country)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Brand.Country.Id)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Category)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Category.CategoryName)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Gender)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Gender.GenderName)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.ModelYear)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.ModelYear)
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Price) грн.
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Colors)
                            </td>
                            <td>
                                @Html.DropDownList("color", new SelectList(Model.Colors.ToList(), "Id", "ColorName"))
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Sizes)
                            </td>
                            <td>
                                @Html.DropDownList("size", new SelectList(Model.Sizes.ToList(), "Id", "SizeName"))
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @Html.DisplayNameFor(model => model.Quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(model => model.Quantity)
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h2>@Html.DisplayNameFor(model => model.Description)</h2>

            @Html.DisplayFor(model => model.Description)
        </div>
    </div>
</div>

DbBicyclesLab/Views/BicycleModels/CommonIndex.cshtml
@model IEnumerable<DbBicyclesLab.Models.BicycleModel>

    @{
        ViewData["Title"] = "Index";
    }

    <style>
        .catalog-grid {
            display: flex;
            flex-direction: row;
            flex-wrap: wrap;
            list-style:none;
        }
        .content_type_catalog {
            width: 100%;
            display: block;
            list-style: none;
        }
        .catalog-grid__cell {
            position: relative;
            width: 33%;
            border-right: 1px solid #e9e9e9;
            border-bottom: 1px solid #e9e9e9;
            box-sizing: border-box;
        }
        .goods-tile {
            position: relative;
            width: 100%;
            overflow: hidden;
        }
        .goods-tile:hover {
            opacity:0.7;
        }
    </style>

    <h1>Моделі велосипедів</h1>

    <section class="content_type_catalog">
        <ul class="catalog-grid">
            @foreach (var item in Model)
            {
                if (item.Image != null)
                {
                    <li class="catalog-grid__cell" style="background-color:white;">
                        <div class="goods-tile" background-color:white;>
                            <a asp-action="CommonDetails" asp-route-id="@item.Id" class="brand-tile">
                               <img style="width:100%; height:auto; text-align:center;" src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Image))" />
                            </a>
                        </div>
                    </li>
                }
                else
                {
                    <li class="catalog-grid__cell" style="background-color:white;">
                        <div class="goods-tile" background-color:white;>
                            <a asp-action="CommonDetails" asp-route-id="@item.Id">
                                @Html.DisplayFor(modelItem => item.ModelName)
                            </a>
                        </div>
                    </li>
                }
            }
        </ul>
    </section>

DbBicyclesLab/Views/BicycleModels/Create.cshtml
@model DbBicyclesLab.Models.BicycleModel

@{
    ViewData["Title"] = "Create";
}

<h1>Створити</h1>

<h4>BicycleModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="BicycleModels" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelName" class="control-label"></label>
                <input asp-for="ModelName" class="form-control" />
                <span asp-validation-for="ModelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.BrandId"></select>
                <a asp-action="Create" asp-controller="Brands">Створити</a>
            </div>
            <div class="form-group">
                <label asp-for="GenderId" class="control-label"></label>
                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.GenderId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbBicyclesLab/Views/BicycleModels/Delete.cshtml
@model DbBicyclesLab.Models.BicycleModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалити</h1>

<h3>Ви впевнені, що бажаєте видалити об'єкт?</h3>
<div>
    <h4>BicycleModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender.GenderName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Назад до списку</a>
    </form>
</div>

DbBicyclesLab/Views/BicycleModels/Details.cshtml
@model DbBicyclesLab.Models.BicycleModel

@{
    ViewData["Title"] = "Details";
}

<h1>Деталі</h1>

<div>
    <h4>BicycleModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand.BrandName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender.GenderName)
        </dd>
                <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        @if (Model.Image != null)
        {<dd class="col-sm-10">
            <img style='width:80px; height:60px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))" />
        </dd>}
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Змінити</a> |
    <a asp-action="Index">Назад до списку</a>
</div>

DbBicyclesLab/Views/BicycleModels/Edit.cshtml
@model DbBicyclesLab.Models.BicycleModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Змінити</h1>

<h4>BicycleModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="BicycleModels" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelName" class="control-label"></label>
                <input asp-for="ModelName" class="form-control" />
                <span asp-validation-for="ModelName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BrandId" class="control-label"></label>
                <select asp-for="BrandId" class="form-control" asp-items="ViewBag.BrandId"></select>
                <span asp-validation-for="BrandId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenderId" class="control-label"></label>
                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.GenderId"></select>
                <span asp-validation-for="GenderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}