DbBicyclesLab/Models/Brand.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace DbBicyclesLab.Models
{
    public partial class Brand
    {
        public Brand()
        {
            BicycleModels = new HashSet<BicycleModel>();
        }

        public int Id { get; set; }
        [Display(Name = "Назва бренду")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        [StringLength(25, ErrorMessage = ErrorMessages.StringLength)]
        public string BrandName { get; set; }
        [Display(Name = "Країна")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        public int CountryId { get; set; }
        [Display(Name = "Представник в Україні")]
        [Required(ErrorMessage = ErrorMessages.Required)]
        public int DealerId { get; set; }
        [Display(Name = "Опис")]
        [StringLength(1500, ErrorMessage = ErrorMessages.StringLength)]
        public string Description { get; set; }
        [Display(Name = "Зображення")]
        public virtual byte[] Image { get; set; }
        [Display(Name = "Країна")]
        public virtual Country Country { get; set; }
        [Display(Name = "Представник в Україні")]
        public virtual AuthorizedDealer Dealer { get; set; }
        public virtual ICollection<BicycleModel> BicycleModels { get; set; }
    }
}

DbBicyclesLab/Models/BrandViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace DbBicyclesLab.Models
{
    public class BrandViewModel
    {
        public int Id { get; set; }
        public string BrandName { get; set; }
        public int CountryId { get; set; }
        public int DealerId { get; set; }
        public string Description { get; set; }
        public virtual Country Country { get; set; }
        public virtual AuthorizedDealer Dealer { get; set; }
        public virtual ICollection<BicycleModel> BicycleModels { get; set; }
        public IFormFile Image { get; set; }
    }
}

DbBicyclesLab/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DbBicyclesLab.Models;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace DbBicyclesLab.Controllers
{
    public class BrandsController : Controller
    {
        private readonly DBBicyclesContext _context;

        public BrandsController(DBBicyclesContext context)
        {
            _context = context;
        }

        // GET: Brands
        public async Task<IActionResult> Index(int? id, string name)
        {
            var dBBicyclesContext = _context.Brands.Include(b => b.Country).Include(b => b.Dealer);
            return View(await dBBicyclesContext.ToListAsync());
        }

        public async Task<IActionResult> CommonIndex()
        {
            var dBBicyclesContext = _context.Brands;//.Include(b => b.BrandName).Include(b => b.Image);
            return View(await dBBicyclesContext.ToListAsync());
        }

        // GET: Brands/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .Include(b => b.Country)
                .Include(b => b.Dealer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        public async Task<IActionResult> CommonDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .Include(b => b.Country)
                .Include(b => b.Dealer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brands/Create
        public IActionResult Create()
        {
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName");
            ViewData["DealerId"] = new SelectList(_context.AuthorizedDealers, "Id", "DealerName");
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /*[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BrandName,CountryId,DealerId,Description")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName", brand.CountryId);
            ViewData["DealerId"] = new SelectList(_context.AuthorizedDealers, "Id", "DealerName", brand.DealerId);
            return View(brand);
        }*/

        [HttpPost]
        public IActionResult Create(BrandViewModel bvm)
        {
            Brand person = new Brand { BrandName = bvm.BrandName, BicycleModels = bvm.BicycleModels, Country = bvm.Country,
                                        CountryId = bvm.CountryId, Dealer = bvm.Dealer, DealerId = bvm.DealerId,
                                            Description = bvm.Description};
            if (bvm.Image != null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(bvm.Image.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)bvm.Image.Length);
                }
                person.Image = imageData;
            }
            _context.Brands.Add(person);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
            //return View(person);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName", brand.CountryId);
            ViewData["DealerId"] = new SelectList(_context.AuthorizedDealers, "Id", "DealerName", brand.DealerId);
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BrandViewModel brand)//[Bind("Id,BrandName,CountryId,DealerId,Description")] Brand brand)
        {
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var person = await _context.Brands.Where(b => b.Id == brand.Id).FirstOrDefaultAsync();

                    person.Id = brand.Id;
                    person.BrandName = brand.BrandName;
                    person.BicycleModels = brand.BicycleModels;
                    person.Country = brand.Country;
                    person.CountryId = brand.CountryId;
                    person.Dealer = brand.Dealer;
                    person.DealerId = brand.DealerId;
                    person.Description = brand.Description;
                    
                    if (brand.Image != null)
                    {
                        byte[] imageData = null;
                        using (var binaryReader = new BinaryReader(brand.Image.OpenReadStream()))
                        {
                            imageData = binaryReader.ReadBytes((int)brand.Image.Length);
                        }
                        person.Image = imageData;
                    }
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CountryId"] = new SelectList(_context.Countries, "Id", "CountryName", brand.CountryId);
            ViewData["DealerId"] = new SelectList(_context.AuthorizedDealers, "Id", "DealerName", brand.DealerId);
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .Include(b => b.Country)
                .Include(b => b.Dealer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brands.Any(e => e.Id == id);
        }

        public async Task<IActionResult> GoToModels(int? id)
        {
            RedirectToActionResult redirectToActionResult = RedirectToAction("Index", "BicycleModels", new { brand = id });
            return await Task.Run<IActionResult>(() =>
            {
                return redirectToActionResult;
            });
        }
    }
}

DbBicyclesLab/Views/Brands/CommonDetails.cshtml
@model DbBicyclesLab.Models.Brand

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>@Html.DisplayFor(model => model.BrandName)</h1>
            <div>
                <a asp-action="CommonIndex">Назад</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            @if (Model.Image != null)
            {
                <img style='width:70%; height:auto; margin:10px; background-color:white; padding:15px' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))" />
            }
        </div>
        <div class="col-6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Дані</th>
                    </tr>
                </thead>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.BrandName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.BrandName)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Country)
                    </td>

                    <td>
                        @Html.DisplayFor(model => model.Country.CountryName)
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.DisplayNameFor(model => model.Dealer)
                    </td>
                    <td>
                        <a href=@Html.DisplayFor(model => model.Dealer.WebsiteAddress)>
                            @Html.DisplayFor(model => model.Dealer.DealerName)
                        </a>
                    </td>
                </tr>
            </table>
        </div>
        </div>
    <div class="row">
        <h2>@Html.DisplayNameFor(model => model.Description)</h2>
        @Html.DisplayFor(model => model.Description)
    </div>
</div>

DbBicyclesLab/Views/Brands/CommonIndex.cshtml
@model IEnumerable<DbBicyclesLab.Models.Brand>

@{
    ViewData["Title"] = "Index";
}

<style>
    .catalog-grid {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        list-style:none;
    }
    .content_type_catalog {
        width: 100%;
        display: block;
        list-style: none;
    }
    .catalog-grid__cell {
        position: relative;
        width: 33%;
        border-right: 1px solid #e9e9e9;
        border-bottom: 1px solid #e9e9e9;
        box-sizing: border-box;
    }
    .goods-tile {
        position: relative;
        width: 100%;
        overflow: hidden;
    }
    .goods-tile:hover {
        opacity:0.7;
    }
</style>

<h1>Бренди</h1>

<div class="container">
    <div class="row">
        <div class="col-12">
            <section class="content_type_catalog">
                <ul class="catalog-grid">
                    @foreach (var item in Model)
                    {
                        if (item.Image != null)
                        {
                            <li class="catalog-grid__cell">
                                <div class="goods-tile">
                                    <a asp-action="CommonDetails" asp-route-id="@item.Id" class="brand-tile">
                                        <img style="width:100%; height:auto; text-align:center;" src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Image))" />
                                    </a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li class="catalog-grid__cell">
                                <div class="goods-tile">
                                    <a asp-action="CommonDetails" asp-route-id="@item.Id">
                                        @Html.DisplayFor(modelItem => item.BrandName)
                                    </a>
                                </div>
                            </li>
                        }
                    }
                </ul>
            </section>
        </div>
    </div>
</div>

DbBicyclesLab/Views/Brands/Create.cshtml
@model DbBicyclesLab.Models.Brand

@{
    ViewData["Title"] = "Create";
}

<h1>Створити</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Brands" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BrandName" class="control-label"></label>
                <input asp-for="BrandName" class="form-control" />
                <span asp-validation-for="BrandName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                <select asp-for="CountryId" class ="form-control" asp-items="ViewBag.CountryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DealerId" class="control-label"></label>
                <select asp-for="DealerId" class ="form-control" asp-items="ViewBag.DealerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbBicyclesLab/Views/Brands/Delete.cshtml
@model DbBicyclesLab.Models.Brand

@{
    ViewData["Title"] = "Delete";
}

<h1>Видалити</h1>

<h3>Ви впевнені, що бажаєте видалити об'єкт?</h3>
<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dealer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dealer.DealerName)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Назад до списку</a>
    </form>
</div>

DbBicyclesLab/Views/Brands/Details.cshtml
@model DbBicyclesLab.Models.Brand

@{
    ViewData["Title"] = "Details";
}

<h1>Деталі</h1>

<div>
    <h4>Brand</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BrandName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BrandName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Dealer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Dealer.DealerName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        @if (Model.Image != null)
        {<dd class="col-sm-10">
            <img style='width:80px; height:60px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))" />
        </dd>}
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Змінити</a> |
    <a asp-action="Index">Назад до списку</a>
</div>

DbBicyclesLab/Views/Brands/Edit.cshtml
@model DbBicyclesLab.Models.Brand

@{
    ViewData["Title"] = "Edit";
}

<h1>Змінити</h1>

<h4>Brand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" asp-controller="Brands" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BrandName" class="control-label"></label>
                <input asp-for="BrandName" class="form-control" />
                <span asp-validation-for="BrandName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label"></label>
                <select asp-for="CountryId" class="form-control" asp-items="ViewBag.CountryId"></select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DealerId" class="control-label"></label>
                <select asp-for="DealerId" class="form-control" asp-items="ViewBag.DealerId"></select>
                <span asp-validation-for="DealerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DbBicyclesLab/Views/Brands/Index.cshtml
@model IEnumerable<DbBicyclesLab.Models.Brand>

@{
    ViewData["Title"] = "Index";
}

<h1>Бренди</h1>

@if (User.IsInRole("admin"))
{
<p>
    <a asp-action="Create">Додати новий</a>
</p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BrandName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dealer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="CommonDetails" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.BrandName)</a>
            </td>
            <td>
                @if (item.Description != null)
                    @(item.Description.ToString().Substring(0, 50)+"...")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country.CountryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dealer.DealerName)
            </td>
            <td>
                @if (item.Image != null)
                {
                    <img style='width:80px; height:60px;' src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Image))" />
                }
            </td>
            <td>
                @if (User.IsInRole("admin"))
                {
                <a asp-action="Edit" asp-route-id="@item.Id">Змінити</a> 
                <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> 
                <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a> 
                }
                <a asp-action="GoToModels" asp-route-id="@item.Id">Моделі</a>
            </td>
        </tr>
}
    </tbody>
</table>